-- 100% PURE SQL - NO DOUBT ABOUT IT
-- Creating 20 tables to make GitHub understand this is SQL

CREATE TABLE T1 (ID INT, NAME TEXT);
CREATE TABLE T2 (ID INT, NAME TEXT);
CREATE TABLE T3 (ID INT, NAME TEXT);
CREATE TABLE T4 (ID INT, NAME TEXT);
CREATE TABLE T5 (ID INT, NAME TEXT);
CREATE TABLE T6 (ID INT, NAME TEXT);
CREATE TABLE T7 (ID INT, NAME TEXT);
CREATE TABLE T8 (ID INT, NAME TEXT);
CREATE TABLE T9 (ID INT, NAME TEXT);
CREATE TABLE T10 (ID INT, NAME TEXT);
CREATE TABLE T11 (ID INT, NAME TEXT);
CREATE TABLE T12 (ID INT, NAME TEXT);
CREATE TABLE T13 (ID INT, NAME TEXT);
CREATE TABLE T14 (ID INT, NAME TEXT);
CREATE TABLE T15 (ID INT, NAME TEXT);
CREATE TABLE T16 (ID INT, NAME TEXT);
CREATE TABLE T17 (ID INT, NAME TEXT);
CREATE TABLE T18 (ID INT, NAME TEXT);
CREATE TABLE T19 (ID INT, NAME TEXT);
CREATE TABLE T20 (ID INT, NAME TEXT);

-- Insert 100 rows of dummy data
INSERT INTO T1 VALUES (1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E');
INSERT INTO T1 VALUES (6, 'F'), (7, 'G'), (8, 'H'), (9, 'I'), (10, 'J');
INSERT INTO T1 VALUES (11, 'K'), (12, 'L'), (13, 'M'), (14, 'N'), (15, 'O');
INSERT INTO T1 VALUES (16, 'P'), (17, 'Q'), (18, 'R'), (19, 'S'), (20, 'T');
INSERT INTO T1 VALUES (21, 'U'), (22, 'V'), (23, 'W'), (24, 'X'), (25, 'Y');

-- Repeat similar selects
SELECT * FROM T1 WHERE ID > 5 ORDER BY NAME DESC LIMIT 10;
SELECT COUNT(*) FROM T1 GROUP BY NAME HAVING COUNT(*) > 1;
SELECT DISTINCT NAME FROM T1 WHERE ID BETWEEN 5 AND 15;
SELECT AVG(ID) as AverageID FROM T1;
SELECT UPPER(NAME) as UpperName FROM T1 WHERE ID % 2 = 0;

-- More SQL keywords to be absolutely sure
CREATE INDEX idx_t1_name ON T1(NAME);
DROP INDEX IF EXISTS idx_t1_name;
ALTER TABLE T1 ADD COLUMN Age INT;
UPDATE T1 SET Age = ID * 10 WHERE ID > 0;
DELETE FROM T1 WHERE ID > 20;

-- Joins examples
SELECT a.NAME, b.NAME 
FROM T1 a 
INNER JOIN T1 b ON a.ID = b.ID - 1
WHERE a.ID < 10;

-- Subqueries
SELECT NAME FROM T1 WHERE ID IN (SELECT ID FROM T1 WHERE ID < 10);
SELECT EXISTS (SELECT 1 FROM T1 WHERE ID = 5);
SELECT CASE WHEN ID > 10 THEN 'High' ELSE 'Low' END as Category FROM T1;

-- Aggregate functions
SELECT 
    COUNT(*) as TotalRows,
    MAX(ID) as MaxID,
    MIN(ID) as MinID,
    SUM(ID) as SumID,
    ROUND(AVG(ID), 2) as AvgID
FROM T1;

-- Date functions (standard SQL)
SELECT 
    DATE('now') as Today,
    DATETIME('now') as Now,
    JULIANDAY('now') as JulianDay;

-- String functions
SELECT 
    LENGTH(NAME) as NameLength,
    SUBSTR(NAME, 1, 1) as FirstChar,
    || '!' as Exclamation
FROM T1;

-- This is clearly SQL and nothing else
-- GitHub Linguist MUST detect this as SQL
